# Generated by Django 4.2.3 on 2023-08-01 00:55

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deletado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=core.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.CharField(default=core.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deletado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('description', models.CharField(db_index=True, max_length=30, verbose_name='descricao da receita')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor da receita')),
                ('expired_at', models.DateField(db_index=True, verbose_name='data de vencimento')),
                ('payed_at', models.DateField(db_index=True, null=True, verbose_name='data do pagamento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='core.category')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
            },
        ),
    ]
